# Generated by Django 4.0.3 on 2022-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0022_alter_booking_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(default='default', max_length=17),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[('new', 'New Booking'), ('pending_approval', 'Pending Approval'), ('pending_lease', 'Pending Lease'), ('pending_slot', 'Pending Slot'), ('rejected', 'Rejected Booking'), ('approved', 'Approved Booking'), ('canceled_before_lease', 'Canceled Before Lease'), ('canceled', 'Canceled Booking'), ('paid', 'Paid Booking'), ('unpaid', 'Unpaid Booking')], default='new', max_length=30),
        ),
    ]
